CREATE TABLE sys_role (
    role_id    NUMBER(10) PRIMARY KEY,
    role_name  VARCHAR2(50) NOT NULL UNIQUE,
    role_desc  VARCHAR2(200)
);

COMMENT ON TABLE sys_role IS '角色表';
COMMENT ON COLUMN sys_role.role_id IS '角色编号';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.role_desc IS '角色说明';

CREATE TABLE sys_menu (
    menu_id     NUMBER(10) PRIMARY KEY,
    menu_name   VARCHAR2(50) NOT NULL,
    menu_url    VARCHAR2(100),
    parent_id   NUMBER(10),
    menu_order  NUMBER(5)
);

COMMENT ON TABLE sys_menu IS '菜单功能表';
COMMENT ON COLUMN sys_menu.menu_id IS '菜单编号';
COMMENT ON COLUMN sys_menu.menu_name IS '菜单名称';
COMMENT ON COLUMN sys_menu.menu_url IS '菜单路径';
COMMENT ON COLUMN sys_menu.parent_id IS '上级菜单编号';
COMMENT ON COLUMN sys_menu.menu_order IS '菜单顺序';

CREATE TABLE sys_user (
    user_id     NUMBER(10) PRIMARY KEY,
    role_id     NUMBER(10),
    username    VARCHAR2(50) NOT NULL UNIQUE,
    password    VARCHAR2(100) NOT NULL,
    real_name   VARCHAR2(50),
    gender      VARCHAR2(10),
    phone       VARCHAR2(20),
    status      VARCHAR2(20),
    create_time DATE DEFAULT SYSDATE,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES sys_role(role_id)
);

COMMENT ON TABLE sys_user IS '用户表';
COMMENT ON COLUMN sys_user.user_id IS '用户编号';
COMMENT ON COLUMN sys_user.role_id IS '角色编号';
COMMENT ON COLUMN sys_user.username IS '登录账号';
COMMENT ON COLUMN sys_user.password IS '登录密码';
COMMENT ON COLUMN sys_user.real_name IS '真实姓名';
COMMENT ON COLUMN sys_user.gender IS '性别';
COMMENT ON COLUMN sys_user.phone IS '联系电话';
COMMENT ON COLUMN sys_user.status IS '用户状态';
COMMENT ON COLUMN sys_user.create_time IS '创建时间';

CREATE TABLE sys_role_menu (
    role_menu_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id      NUMBER(10) NOT NULL,
    menu_id      NUMBER(10) NOT NULL,
    CONSTRAINT fk_rm_role FOREIGN KEY (role_id) REFERENCES sys_role(role_id) ON DELETE CASCADE,
    CONSTRAINT fk_rm_menu FOREIGN KEY (menu_id) REFERENCES sys_menu(menu_id) ON DELETE CASCADE,
    CONSTRAINT uk_role_menu UNIQUE (role_id, menu_id)
);

COMMENT ON TABLE sys_role_menu IS '权限中间表：定义哪些角色可以访问哪些菜单';

CREATE TABLE supplier (
    supplier_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    supplier_name  VARCHAR2(100) NOT NULL,
    contact_name   VARCHAR2(50),
    phone          VARCHAR2(20),
    email          VARCHAR2(100),
    address        VARCHAR2(200),
    credit_level   VARCHAR2(20),
    payment_cycle  NUMBER(5),
    CONSTRAINT pk_supplier PRIMARY KEY (supplier_id)
);

COMMENT ON TABLE supplier IS '供应商信息表';
COMMENT ON COLUMN supplier.supplier_id IS '供应商唯一标识 (主键)';
COMMENT ON COLUMN supplier.credit_level IS '供应商信誉等级';
COMMENT ON COLUMN supplier.payment_cycle IS '约定结算周期（天数）';

CREATE TABLE product_category (
    category_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL UNIQUE,
    category_desc VARCHAR2(200),
    status        VARCHAR2(20) DEFAULT '启用'
);

COMMENT ON TABLE product_category IS '商品类别表';
COMMENT ON COLUMN product_category.category_name IS '类别名称，如食品、日用品等';

CREATE TABLE member (
    member_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    member_name    VARCHAR2(100) NOT NULL,
    gender         VARCHAR2(10) CHECK (gender IN ('男', '女', '未知')),
    phone          VARCHAR2(20) NOT NULL,
    birthday       DATE,
    points         NUMBER(10) DEFAULT 0,
    total_amount   NUMBER(12, 2) DEFAULT 0.00,
    level_name     VARCHAR2(20) DEFAULT '普通会员',
    create_time    DATE DEFAULT SYSDATE,
    CONSTRAINT pk_member PRIMARY KEY (member_id),
    CONSTRAINT uk_member_phone UNIQUE (phone)
);

COMMENT ON TABLE member IS '会员信息表';
COMMENT ON COLUMN member.member_id IS '会员唯一标识 (主键)';
COMMENT ON COLUMN member.phone IS '会员手机号 (唯一约束)';
COMMENT ON COLUMN member.points IS '当前剩余积分';
COMMENT ON COLUMN member.level_name IS '会员等级（硬编码文本）';

CREATE TABLE product (
    product_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    NUMBER(10) NOT NULL,
    supplier_id    NUMBER(10) NOT NULL,
    product_name   VARCHAR2(100) NOT NULL,
    barcode        VARCHAR2(50) UNIQUE,
    specification  VARCHAR2(100),
    purchase_price NUMBER(10, 2) DEFAULT 0,
    sale_price     NUMBER(10, 2) DEFAULT 0,
    stock_warning  NUMBER(10) DEFAULT 10,
    unit           VARCHAR2(20),
    status         VARCHAR2(20) DEFAULT '在售',
    CONSTRAINT fk_prod_category FOREIGN KEY (category_id) REFERENCES product_category(category_id),
    CONSTRAINT fk_prod_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id)
);

COMMENT ON TABLE product IS '商品基础资料表';

CREATE TABLE purchase_order (
    order_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    order_code      VARCHAR2(20) NOT NULL,
    supplier_id     NUMBER(10),
    purchase_date   DATE DEFAULT TRUNC(SYSDATE),
    total_amount    NUMBER(12, 2),
    applicant_id    NUMBER(10),
    approver_id     NUMBER(10),
    status          VARCHAR2(20) DEFAULT '待审批',
    CONSTRAINT pk_purchase_order PRIMARY KEY (order_id),
    CONSTRAINT uk_purchase_order_code UNIQUE (order_code),
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id),
    CONSTRAINT fk_po_applicant FOREIGN KEY (applicant_id) REFERENCES sys_user(user_id),
    CONSTRAINT fk_po_approver FOREIGN KEY (approver_id) REFERENCES sys_user(user_id),
    CONSTRAINT ck_po_status CHECK (status IN ('待审批', '已审批', '已入库', '已作废'))
);

COMMENT ON TABLE purchase_order IS '采购订单主表';
COMMENT ON COLUMN purchase_order.order_id IS '采购订单唯一标识 (主键)';
COMMENT ON COLUMN purchase_order.order_code IS '采购单据编码 (系统生成, 唯一)';
COMMENT ON COLUMN purchase_order.supplier_id IS '供应商ID (关联supplier表)';
COMMENT ON COLUMN purchase_order.applicant_id IS '申请用户ID (关联sys_user表)';
COMMENT ON COLUMN purchase_order.approver_id IS '审批用户ID (关联sys_user表)';
COMMENT ON COLUMN purchase_order.status IS '单据状态';

CREATE TABLE purchase_order_detail (
    purchase_detail_id NUMBER(10) NOT NULL,
    purchase_id        NUMBER(10) NOT NULL,
    product_id         NUMBER(10) NOT NULL,
    purchase_quantity  NUMBER(10),
    purchase_price     NUMBER(10, 2),
    CONSTRAINT pk_purchase_detail PRIMARY KEY (purchase_detail_id),
    CONSTRAINT fk_pur_detail_purchase FOREIGN KEY (purchase_id) REFERENCES purchase_order(order_id),
    CONSTRAINT fk_pur_detail_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE purchase_order_detail IS '采购订单明细表';
COMMENT ON COLUMN purchase_order_detail.purchase_detail_id IS '明细编号';
COMMENT ON COLUMN purchase_order_detail.purchase_id IS '采购单编号';
COMMENT ON COLUMN purchase_order_detail.product_id IS '商品编号';
COMMENT ON COLUMN purchase_order_detail.purchase_quantity IS '采购数量';
COMMENT ON COLUMN purchase_order_detail.purchase_price IS '采购单价';

CREATE TABLE sale_order (
    sale_id         NUMBER(10) NOT NULL,
    sale_no         VARCHAR2(50) NOT NULL,
    member_id       NUMBER(10),
    user_id         NUMBER(10) NOT NULL,
    sale_date       DATE,
    total_amount    NUMBER(12, 2),
    discount_amount NUMBER(12, 2),
    paid_amount     NUMBER(12, 2),
    pay_type        VARCHAR2(20),
    status          VARCHAR2(20),
    CONSTRAINT pk_sale_order PRIMARY KEY (sale_id),
    CONSTRAINT uk_sale_no UNIQUE (sale_no),
    CONSTRAINT fk_sale_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_sale_user FOREIGN KEY (user_id) REFERENCES sys_user(user_id)
);

COMMENT ON TABLE sale_order IS '销售订单表';
COMMENT ON COLUMN sale_order.sale_id IS '销售单编号';
COMMENT ON COLUMN sale_order.sale_no IS '销售单号';
COMMENT ON COLUMN sale_order.member_id IS '会员编号';
COMMENT ON COLUMN sale_order.user_id IS '收银员编号';
COMMENT ON COLUMN sale_order.sale_date IS '销售日期';
COMMENT ON COLUMN sale_order.total_amount IS '原始总金额';
COMMENT ON COLUMN sale_order.discount_amount IS '优惠金额';
COMMENT ON COLUMN sale_order.paid_amount IS '实付金额';
COMMENT ON COLUMN sale_order.pay_type IS '支付方式';
COMMENT ON COLUMN sale_order.status IS '销售单状态';

CREATE TABLE sale_order_detail (
    sale_detail_id NUMBER(10) NOT NULL,
    sale_id        NUMBER(10) NOT NULL,
    product_id     NUMBER(10) NOT NULL,
    sale_quantity  NUMBER(10),
    sale_price     NUMBER(10, 2),
    CONSTRAINT pk_sale_order_detail PRIMARY KEY (sale_detail_id),
    CONSTRAINT fk_sale_detail_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    CONSTRAINT fk_sale_detail_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE sale_order_detail IS '销售单明细表';
COMMENT ON COLUMN sale_order_detail.sale_detail_id IS '明细编号';
COMMENT ON COLUMN sale_order_detail.sale_id IS '销售单编号';
COMMENT ON COLUMN sale_order_detail.product_id IS '商品编号';
COMMENT ON COLUMN sale_order_detail.sale_quantity IS '销售数量';
COMMENT ON COLUMN sale_order_detail.sale_price IS '销售单价';

CREATE TABLE inventory (
    inventory_id     NUMBER(10) NOT NULL,
    product_id       NUMBER(10) NOT NULL,
    current_stock    NUMBER(10) NOT NULL,
    last_update_time DATE NOT NULL,
    CONSTRAINT pk_inventory PRIMARY KEY (inventory_id),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON COLUMN inventory.inventory_id IS '库存编号';
COMMENT ON COLUMN inventory.product_id IS '商品编号，关联商品表';
COMMENT ON COLUMN inventory.current_stock IS '当前库存量';
COMMENT ON COLUMN inventory.last_update_time IS '最后更新时间';

CREATE TABLE inventory_record (
    record_id   NUMBER(10) NOT NULL,
    product_id  NUMBER(10) NOT NULL,
    record_type VARCHAR2(20) NOT NULL,
    source_no   VARCHAR2(50),
    change_qty  NUMBER(10) NOT NULL,
    remain_qty  NUMBER(10) NOT NULL,
    operator_id NUMBER(10) NOT NULL,
    record_time DATE NOT NULL,
    remark      VARCHAR2(200),
    CONSTRAINT pk_inventory_record PRIMARY KEY (record_id),
    CONSTRAINT fk_inv_record_product FOREIGN KEY (product_id) REFERENCES product(product_id),
    CONSTRAINT fk_inv_record_user FOREIGN KEY (operator_id) REFERENCES sys_user(user_id)
);

COMMENT ON COLUMN inventory_record.record_id IS '流水编号';
COMMENT ON COLUMN inventory_record.product_id IS '商品编号';
COMMENT ON COLUMN inventory_record.record_type IS '流水类型(入库/销售/退货/盘点)';
COMMENT ON COLUMN inventory_record.source_no IS '来源单号';
COMMENT ON COLUMN inventory_record.change_qty IS '变动数量';
COMMENT ON COLUMN inventory_record.remain_qty IS '变动后库存';
COMMENT ON COLUMN inventory_record.operator_id IS '操作人编号';
COMMENT ON COLUMN inventory_record.record_time IS '记录时间';
COMMENT ON COLUMN inventory_record.remark IS '备注';

CREATE TABLE return_order (
    return_id     NUMBER(10) NOT NULL,
    return_no     VARCHAR2(50) NOT NULL,
    sale_id       NUMBER(10) NOT NULL,
    member_id     NUMBER(10),
    operator_id   NUMBER(10) NOT NULL,
    return_date   DATE NOT NULL,
    refund_amount NUMBER(12, 2) NOT NULL,
    status        VARCHAR2(20) NOT NULL,
    remark        VARCHAR2(200),
    CONSTRAINT pk_return_order PRIMARY KEY (return_id),
    CONSTRAINT uk_return_order_no UNIQUE (return_no),
    CONSTRAINT fk_return_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    CONSTRAINT fk_return_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_return_operator FOREIGN KEY (operator_id) REFERENCES sys_user(user_id)
);

COMMENT ON COLUMN return_order.return_id IS '退货单编号';
COMMENT ON COLUMN return_order.return_no IS '退货单号';
COMMENT ON COLUMN return_order.sale_id IS '对应销售单编号';
COMMENT ON COLUMN return_order.member_id IS '会员编号';
COMMENT ON COLUMN return_order.operator_id IS '经办人编号';
COMMENT ON COLUMN return_order.return_date IS '退货日期';
COMMENT ON COLUMN return_order.refund_amount IS '退款金额';
COMMENT ON COLUMN return_order.status IS '退货状态';
COMMENT ON COLUMN return_order.remark IS '备注';

CREATE TABLE return_order_detail (
    return_detail_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id        NUMBER(10) NOT NULL,
    product_id       NUMBER(10) NOT NULL,
    quantity         NUMBER(10) NOT NULL,
    refund_price     NUMBER(10, 2) NOT NULL,
    subtotal         NUMBER(12, 2) NOT NULL,
    CONSTRAINT fk_rod_return FOREIGN KEY (return_id) REFERENCES return_order(return_id) ON DELETE CASCADE,
    CONSTRAINT fk_rod_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE return_order_detail IS '退货单明细表：记录每一笔退货业务中包含的具体商品、数量及退款单价';
COMMENT ON COLUMN return_order_detail.refund_price IS '退货单价';
COMMENT ON COLUMN return_order_detail.subtotal IS '该笔商品退款总计金额';

CREATE TABLE point_record (
    point_record_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       NUMBER(10) NOT NULL,
    sale_id         NUMBER(10),
    change_type     VARCHAR2(20) NOT NULL,
    change_points   NUMBER(10) NOT NULL,
    remain_points   NUMBER(10) NOT NULL,
    record_time     DATE DEFAULT SYSDATE,
    remark          VARCHAR2(200),
    CONSTRAINT fk_pr_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_pr_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    CONSTRAINT ck_pr_type CHECK (change_type IN ('增加','扣减','抵现'))
);

COMMENT ON TABLE point_record IS '积分流水表：记录会员积分的每一次增减变动历史';
COMMENT ON COLUMN point_record.sale_id IS '关联销售单，记录是哪笔交易产生的积分变动；若是其他活动导致积分变化时可为空';

CREATE TABLE supplier_settlement (
    settlement_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id       NUMBER(10) NOT NULL,
    purchase_id       NUMBER(10) NOT NULL,
    settlement_date   DATE DEFAULT SYSDATE,
    settlement_amount NUMBER(12, 2) NOT NULL,
    paid_amount       NUMBER(12, 2) DEFAULT 0,
    unpaid_amount     NUMBER(12, 2) NOT NULL,
    status            VARCHAR2(20) NOT NULL,
    remark            VARCHAR2(200),
    CONSTRAINT fk_ss_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id),
    CONSTRAINT fk_ss_purchase FOREIGN KEY (purchase_id) REFERENCES purchase_order(order_id),
    CONSTRAINT ck_ss_status CHECK (status IN ('未结算', '已结算', '部分结算'))
);

COMMENT ON TABLE supplier_settlement IS '供应商结算表：管理与供应商的财务结账情况';
