-- ============================================================
-- 清理旧表（全库 DROP，方便反复初始化）
-- ============================================================
BEGIN
   FOR t IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

CREATE TABLE sys_role (
    role_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name  VARCHAR2(50) NOT NULL UNIQUE,
    role_desc  VARCHAR2(200)
);

COMMENT ON TABLE sys_role IS '角色表';
COMMENT ON COLUMN sys_role.role_id IS '角色编号';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.role_desc IS '角色说明';

CREATE TABLE sys_menu (
    menu_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_name   VARCHAR2(50) NOT NULL,
    menu_url    VARCHAR2(100),
    parent_id   NUMBER(10),
    menu_order  NUMBER(5)
);

COMMENT ON TABLE sys_menu IS '菜单功能表';
COMMENT ON COLUMN sys_menu.menu_id IS '菜单编号';
COMMENT ON COLUMN sys_menu.menu_name IS '菜单名称';
COMMENT ON COLUMN sys_menu.menu_url IS '菜单路径';
COMMENT ON COLUMN sys_menu.parent_id IS '上级菜单编号';
COMMENT ON COLUMN sys_menu.menu_order IS '菜单顺序';

CREATE TABLE sys_user (
    user_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     NUMBER(10),
    username    VARCHAR2(50) NOT NULL UNIQUE,
    password    VARCHAR2(100) NOT NULL,
    real_name   VARCHAR2(50),
    gender      VARCHAR2(10),
    phone       VARCHAR2(20),
    status      VARCHAR2(20),
    create_time DATE DEFAULT SYSDATE,
    CONSTRAINT fk_user_role FOREIGN KEY (role_id) REFERENCES sys_role(role_id),
    CONSTRAINT ck_user_status CHECK (status IN ('启用', '禁用'))
);

COMMENT ON TABLE sys_user IS '用户表';
COMMENT ON COLUMN sys_user.user_id IS '用户编号';
COMMENT ON COLUMN sys_user.role_id IS '角色编号';
COMMENT ON COLUMN sys_user.username IS '登录账号';
COMMENT ON COLUMN sys_user.password IS '登录密码';
COMMENT ON COLUMN sys_user.real_name IS '真实姓名';
COMMENT ON COLUMN sys_user.gender IS '性别';
COMMENT ON COLUMN sys_user.phone IS '联系电话';
COMMENT ON COLUMN sys_user.status IS '用户状态';
COMMENT ON COLUMN sys_user.create_time IS '创建时间';

CREATE INDEX idx_sys_user_role ON sys_user(role_id);

CREATE TABLE sys_role_menu (
    role_menu_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id      NUMBER(10) NOT NULL,
    menu_id      NUMBER(10) NOT NULL,
    CONSTRAINT fk_rm_role FOREIGN KEY (role_id) REFERENCES sys_role(role_id) ON DELETE CASCADE,
    CONSTRAINT fk_rm_menu FOREIGN KEY (menu_id) REFERENCES sys_menu(menu_id) ON DELETE CASCADE,
    CONSTRAINT uk_role_menu UNIQUE (role_id, menu_id)
);

COMMENT ON TABLE sys_role_menu IS '权限中间表：定义哪些角色可以访问哪些菜单';

CREATE INDEX idx_srm_role ON sys_role_menu(role_id);
CREATE INDEX idx_srm_menu ON sys_role_menu(menu_id);

CREATE TABLE supplier (
    supplier_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    supplier_name  VARCHAR2(100) NOT NULL,
    contact_name   VARCHAR2(50),
    phone          VARCHAR2(20),
    email          VARCHAR2(100),
    address        VARCHAR2(200),
    credit_level   VARCHAR2(20),
    payment_cycle  NUMBER(5),
    min_order_qty  NUMBER(10) DEFAULT 0,
    bank_name      VARCHAR2(100),
    bank_account   VARCHAR2(50),
    CONSTRAINT pk_supplier PRIMARY KEY (supplier_id)
);

COMMENT ON TABLE supplier IS '供应商信息表';
COMMENT ON COLUMN supplier.supplier_id IS '供应商唯一标识 (主键)';
COMMENT ON COLUMN supplier.credit_level IS '供应商信誉等级';
COMMENT ON COLUMN supplier.payment_cycle IS '约定结算周期（天数）';
COMMENT ON COLUMN supplier.min_order_qty IS '最小起订量';
COMMENT ON COLUMN supplier.bank_name IS '开户银行名称';
COMMENT ON COLUMN supplier.bank_account IS '银行账号';

CREATE TABLE product_category (
    category_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR2(50) NOT NULL UNIQUE,
    category_desc VARCHAR2(200),
    status        VARCHAR2(20) DEFAULT '启用',
    CONSTRAINT ck_cat_status CHECK (status IN ('启用', '禁用'))
);

COMMENT ON TABLE product_category IS '商品类别表';
COMMENT ON COLUMN product_category.category_name IS '类别名称，如食品、日用品等';

CREATE TABLE member (
    member_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    member_name    VARCHAR2(100) NOT NULL,
    gender         VARCHAR2(10) CHECK (gender IN ('男', '女', '未知')),
    phone          VARCHAR2(20) NOT NULL,
    birthday       DATE,
    points         NUMBER(10) DEFAULT 0,
    member_tag     VARCHAR2(100),
    total_amount   NUMBER(12, 2) DEFAULT 0.00,
    level_name     VARCHAR2(20) DEFAULT '普通会员',
    discount_rate  NUMBER(5, 2) DEFAULT 1.00,
    create_time    DATE DEFAULT SYSDATE,
    CONSTRAINT pk_member PRIMARY KEY (member_id),
    CONSTRAINT uk_member_phone UNIQUE (phone),
    CONSTRAINT ck_member_level CHECK (level_name IN ('普通会员', '黄金会员', '钻石会员'))
);

COMMENT ON TABLE member IS '会员信息表';
COMMENT ON COLUMN member.member_id IS '会员唯一标识 (主键)';
COMMENT ON COLUMN member.phone IS '会员手机号 (唯一约束)';
COMMENT ON COLUMN member.points IS '当前剩余积分';
COMMENT ON COLUMN member.member_tag IS '会员标签（如"学生""VIP"等）';
COMMENT ON COLUMN member.level_name IS '会员等级（普通/黄金/钻石）';
COMMENT ON COLUMN member.discount_rate IS '会员等级对应的基础折扣率（如0.95=95折）';

CREATE TABLE product (
    product_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    NUMBER(10) NOT NULL,
    supplier_id    NUMBER(10) NOT NULL,
    product_name   VARCHAR2(100) NOT NULL,
    barcode        VARCHAR2(50) UNIQUE,
    specification  VARCHAR2(100),
    purchase_price NUMBER(10, 2) DEFAULT 0,
    sale_price        NUMBER(10, 2) DEFAULT 0,
    is_promotion      VARCHAR2(10) DEFAULT '否',
    promotion_price   NUMBER(10, 2),
    stock_warning  NUMBER(10) DEFAULT 10,
    unit           VARCHAR2(20),
    status         VARCHAR2(20) DEFAULT '在售',
    CONSTRAINT ck_prod_status CHECK (status IN ('在售', '下架', '停售')),
    CONSTRAINT ck_promotion CHECK (is_promotion IN ('是', '否')),
    CONSTRAINT fk_prod_category FOREIGN KEY (category_id) REFERENCES product_category(category_id),
    CONSTRAINT fk_prod_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id)
);

COMMENT ON TABLE product IS '商品基础资料表';

CREATE INDEX idx_product_category ON product(category_id);
CREATE INDEX idx_product_supplier ON product(supplier_id);

CREATE TABLE purchase_order (
    order_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    order_code      VARCHAR2(20) NOT NULL,
    supplier_id     NUMBER(10),
    purchase_date   DATE DEFAULT TRUNC(SYSDATE),
    total_amount    NUMBER(12, 2),
    applicant_id    NUMBER(10),
    approver_id     NUMBER(10),
    status          VARCHAR2(20) DEFAULT '待审批',
    create_time     DATE DEFAULT SYSDATE,
    update_time     DATE,
    CONSTRAINT pk_purchase_order PRIMARY KEY (order_id),
    CONSTRAINT uk_purchase_order_code UNIQUE (order_code),
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id),
    CONSTRAINT fk_po_applicant FOREIGN KEY (applicant_id) REFERENCES sys_user(user_id),
    CONSTRAINT fk_po_approver FOREIGN KEY (approver_id) REFERENCES sys_user(user_id),
    CONSTRAINT ck_po_status CHECK (status IN ('待审批', '已审批', '已入库', '已作废'))
);

COMMENT ON TABLE purchase_order IS '采购订单主表';
COMMENT ON COLUMN purchase_order.order_id IS '采购订单唯一标识 (主键)';
COMMENT ON COLUMN purchase_order.order_code IS '采购单据编码 (系统生成, 唯一)';
COMMENT ON COLUMN purchase_order.supplier_id IS '供应商ID (关联supplier表)';
COMMENT ON COLUMN purchase_order.applicant_id IS '申请用户ID (关联sys_user表)';
COMMENT ON COLUMN purchase_order.approver_id IS '审批用户ID (关联sys_user表)';
COMMENT ON COLUMN purchase_order.status IS '单据状态';
COMMENT ON COLUMN purchase_order.create_time IS '订单创建时间';
COMMENT ON COLUMN purchase_order.update_time IS '最后状态变更时间';

CREATE INDEX idx_po_supplier ON purchase_order(supplier_id);
CREATE INDEX idx_po_applicant ON purchase_order(applicant_id);
CREATE INDEX idx_po_approver ON purchase_order(approver_id);

CREATE TABLE purchase_order_detail (
    purchase_detail_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id        NUMBER(10) NOT NULL,
    product_id         NUMBER(10) NOT NULL,
    purchase_quantity  NUMBER(10),
    purchase_price     NUMBER(10, 2),
    CONSTRAINT fk_pur_detail_purchase FOREIGN KEY (purchase_id) REFERENCES purchase_order(order_id),
    CONSTRAINT fk_pur_detail_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE purchase_order_detail IS '采购订单明细表';
COMMENT ON COLUMN purchase_order_detail.purchase_detail_id IS '明细编号';
COMMENT ON COLUMN purchase_order_detail.purchase_id IS '采购单编号';
COMMENT ON COLUMN purchase_order_detail.product_id IS '商品编号';
COMMENT ON COLUMN purchase_order_detail.purchase_quantity IS '采购数量';
COMMENT ON COLUMN purchase_order_detail.purchase_price IS '采购单价';

CREATE INDEX idx_pod_purchase ON purchase_order_detail(purchase_id);
CREATE INDEX idx_pod_product ON purchase_order_detail(product_id);

CREATE TABLE sale_order (
    sale_id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_no         VARCHAR2(50) NOT NULL,
    member_id       NUMBER(10),
    user_id         NUMBER(10) NOT NULL,
    sale_date       DATE,
    total_amount    NUMBER(12, 2),
    discount_amount NUMBER(12, 2),
    paid_amount     NUMBER(12, 2),
    pay_type        VARCHAR2(20),
    status          VARCHAR2(20) DEFAULT '待支付',
    create_time     DATE DEFAULT SYSDATE,
    update_time     DATE,
    CONSTRAINT ck_sale_status CHECK (status IN ('待支付', '已完成', '已取消')),
    CONSTRAINT uk_sale_no UNIQUE (sale_no),
    CONSTRAINT fk_sale_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_sale_user FOREIGN KEY (user_id) REFERENCES sys_user(user_id)
);

COMMENT ON TABLE sale_order IS '销售订单表';
COMMENT ON COLUMN sale_order.sale_id IS '销售单编号';
COMMENT ON COLUMN sale_order.sale_no IS '销售单号';
COMMENT ON COLUMN sale_order.member_id IS '会员编号';
COMMENT ON COLUMN sale_order.user_id IS '收银员编号';
COMMENT ON COLUMN sale_order.sale_date IS '销售日期';
COMMENT ON COLUMN sale_order.total_amount IS '原始总金额';
COMMENT ON COLUMN sale_order.discount_amount IS '优惠金额';
COMMENT ON COLUMN sale_order.paid_amount IS '实付金额';
COMMENT ON COLUMN sale_order.pay_type IS '支付方式';
COMMENT ON COLUMN sale_order.status IS '销售单状态';
COMMENT ON COLUMN sale_order.create_time IS '订单创建时间';
COMMENT ON COLUMN sale_order.update_time IS '最后状态变更时间';

CREATE INDEX idx_sale_member ON sale_order(member_id);
CREATE INDEX idx_sale_user ON sale_order(user_id);

CREATE TABLE sale_order_detail (
    sale_detail_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id        NUMBER(10) NOT NULL,
    product_id     NUMBER(10) NOT NULL,
    sale_quantity  NUMBER(10),
    sale_price     NUMBER(10, 2),
    CONSTRAINT fk_sale_detail_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    CONSTRAINT fk_sale_detail_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE sale_order_detail IS '销售单明细表';
COMMENT ON COLUMN sale_order_detail.sale_detail_id IS '明细编号';
COMMENT ON COLUMN sale_order_detail.sale_id IS '销售单编号';
COMMENT ON COLUMN sale_order_detail.product_id IS '商品编号';
COMMENT ON COLUMN sale_order_detail.sale_quantity IS '销售数量';
COMMENT ON COLUMN sale_order_detail.sale_price IS '销售单价';

CREATE INDEX idx_sod_sale ON sale_order_detail(sale_id);
CREATE INDEX idx_sod_product ON sale_order_detail(product_id);

CREATE TABLE warehouse (
    warehouse_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_name VARCHAR2(100) NOT NULL,
    address        VARCHAR2(200),
    status         VARCHAR2(20) DEFAULT '启用',
    create_time    DATE DEFAULT SYSDATE,
    CONSTRAINT ck_wh_status CHECK (status IN ('启用', '禁用'))
);

COMMENT ON TABLE warehouse IS '仓库/门店表：管理系统中的物理仓储节点';
COMMENT ON COLUMN warehouse.warehouse_id IS '仓库编号';
COMMENT ON COLUMN warehouse.warehouse_name IS '仓库/门店名称';
COMMENT ON COLUMN warehouse.address IS '仓库地址';
COMMENT ON COLUMN warehouse.status IS '状态（启用/禁用）';

CREATE TABLE inventory (
    inventory_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       NUMBER(10) NOT NULL,
    warehouse_id     NUMBER(10) NOT NULL,
    current_stock    NUMBER(10) NOT NULL,
    last_update_time DATE NOT NULL,
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES product(product_id),
    CONSTRAINT fk_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse(warehouse_id),
    CONSTRAINT uk_inv_prod_wh UNIQUE (product_id, warehouse_id)
);

COMMENT ON COLUMN inventory.inventory_id IS '库存编号';
COMMENT ON COLUMN inventory.product_id IS '商品编号，关联商品表';
COMMENT ON COLUMN inventory.warehouse_id IS '仓库编号，关联仓库表';
COMMENT ON COLUMN inventory.current_stock IS '当前库存量';
COMMENT ON COLUMN inventory.last_update_time IS '最后更新时间';

CREATE INDEX idx_inventory_product ON inventory(product_id);
CREATE INDEX idx_inventory_warehouse ON inventory(warehouse_id);

CREATE TABLE inventory_record (
    record_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  NUMBER(10) NOT NULL,
    record_type VARCHAR2(20) NOT NULL,
    source_no   VARCHAR2(50),
    change_qty  NUMBER(10) NOT NULL,
    remain_qty  NUMBER(10) NOT NULL,
    operator_id NUMBER(10) NOT NULL,
    record_time DATE NOT NULL,
    remark      VARCHAR2(200),
    CONSTRAINT fk_inv_record_product FOREIGN KEY (product_id) REFERENCES product(product_id),
    CONSTRAINT fk_inv_record_user FOREIGN KEY (operator_id) REFERENCES sys_user(user_id)
);

COMMENT ON COLUMN inventory_record.record_id IS '流水编号';
COMMENT ON COLUMN inventory_record.product_id IS '商品编号';
COMMENT ON COLUMN inventory_record.record_type IS '流水类型(入库/销售/退货/盘点)';
COMMENT ON COLUMN inventory_record.source_no IS '来源单号';
COMMENT ON COLUMN inventory_record.change_qty IS '变动数量';
COMMENT ON COLUMN inventory_record.remain_qty IS '变动后库存';
COMMENT ON COLUMN inventory_record.operator_id IS '操作人编号';
COMMENT ON COLUMN inventory_record.record_time IS '记录时间';
COMMENT ON COLUMN inventory_record.remark IS '备注';

CREATE INDEX idx_ir_product ON inventory_record(product_id);
CREATE INDEX idx_ir_operator ON inventory_record(operator_id);

CREATE TABLE return_order (
    return_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no     VARCHAR2(50) NOT NULL,
    sale_id       NUMBER(10) NOT NULL,
    member_id     NUMBER(10),
    operator_id   NUMBER(10) NOT NULL,
    return_date   DATE NOT NULL,
    refund_amount NUMBER(12, 2) NOT NULL,
    status        VARCHAR2(20) DEFAULT '待处理' NOT NULL,
    create_time   DATE DEFAULT SYSDATE,
    update_time   DATE,
    remark        VARCHAR2(200),
    CONSTRAINT ck_return_status CHECK (status IN ('待处理', '已完成', '已拒绝')),
    CONSTRAINT uk_return_order_no UNIQUE (return_no),
    CONSTRAINT fk_return_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    CONSTRAINT fk_return_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_return_operator FOREIGN KEY (operator_id) REFERENCES sys_user(user_id)
);

COMMENT ON COLUMN return_order.return_id IS '退货单编号';
COMMENT ON COLUMN return_order.return_no IS '退货单号';
COMMENT ON COLUMN return_order.sale_id IS '对应销售单编号';
COMMENT ON COLUMN return_order.member_id IS '会员编号';
COMMENT ON COLUMN return_order.operator_id IS '经办人编号';
COMMENT ON COLUMN return_order.return_date IS '退货日期';
COMMENT ON COLUMN return_order.refund_amount IS '退款金额';
COMMENT ON COLUMN return_order.status IS '退货状态';
COMMENT ON COLUMN return_order.create_time IS '订单创建时间';
COMMENT ON COLUMN return_order.update_time IS '最后状态变更时间';
COMMENT ON COLUMN return_order.remark IS '备注';

CREATE INDEX idx_return_sale ON return_order(sale_id);
CREATE INDEX idx_return_member ON return_order(member_id);
CREATE INDEX idx_return_operator ON return_order(operator_id);

CREATE TABLE return_order_detail (
    return_detail_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id        NUMBER(10) NOT NULL,
    product_id       NUMBER(10) NOT NULL,
    quantity         NUMBER(10) NOT NULL,
    refund_price     NUMBER(10, 2) NOT NULL,
    subtotal         NUMBER(12, 2) NOT NULL,
    CONSTRAINT fk_rod_return FOREIGN KEY (return_id) REFERENCES return_order(return_id) ON DELETE CASCADE,
    CONSTRAINT fk_rod_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE return_order_detail IS '退货单明细表：记录每一笔退货业务中包含的具体商品、数量及退款单价';
COMMENT ON COLUMN return_order_detail.refund_price IS '退货单价';
COMMENT ON COLUMN return_order_detail.subtotal IS '该笔商品退款总计金额';

CREATE INDEX idx_rod_return ON return_order_detail(return_id);
CREATE INDEX idx_rod_product ON return_order_detail(product_id);

CREATE TABLE point_record (
    point_record_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       NUMBER(10) NOT NULL,
    sale_id         NUMBER(10),
    change_type     VARCHAR2(20) NOT NULL,
    change_points   NUMBER(10) NOT NULL,
    remain_points   NUMBER(10) NOT NULL,
    record_time     DATE DEFAULT SYSDATE,
    remark          VARCHAR2(200),
    CONSTRAINT fk_pr_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_pr_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    CONSTRAINT ck_pr_type CHECK (change_type IN ('增加','扣减','抵现'))
);

COMMENT ON TABLE point_record IS '积分流水表：记录会员积分的每一次增减变动历史';
COMMENT ON COLUMN point_record.sale_id IS '关联销售单，记录是哪笔交易产生的积分变动；若是其他活动导致积分变化时可为空';

CREATE INDEX idx_pr_member ON point_record(member_id);
CREATE INDEX idx_pr_sale ON point_record(sale_id);

CREATE TABLE supplier_settlement (
    settlement_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id       NUMBER(10) NOT NULL,
    purchase_id       NUMBER(10) NOT NULL,
    settlement_date   DATE DEFAULT SYSDATE,
    settlement_amount NUMBER(12, 2) NOT NULL,
    paid_amount       NUMBER(12, 2) DEFAULT 0,
    unpaid_amount     NUMBER(12, 2) NOT NULL,
    status            VARCHAR2(20) NOT NULL,
    remark            VARCHAR2(200),
    CONSTRAINT fk_ss_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id),
    CONSTRAINT fk_ss_purchase FOREIGN KEY (purchase_id) REFERENCES purchase_order(order_id),
    CONSTRAINT ck_ss_status CHECK (status IN ('未结算', '已结算', '部分结算'))
);

COMMENT ON TABLE supplier_settlement IS '供应商结算表：管理与供应商的财务结账情况';

CREATE INDEX idx_ss_supplier ON supplier_settlement(supplier_id);
CREATE INDEX idx_ss_purchase ON supplier_settlement(purchase_id);

-- ============================================================
-- 以下为新增表（对应新版功能点）
-- ============================================================

-- 19. order_status_log
CREATE TABLE order_status_log (
    log_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_type  VARCHAR2(20) NOT NULL,
    order_id    NUMBER(10) NOT NULL,
    old_status  VARCHAR2(20),
    new_status  VARCHAR2(20) NOT NULL,
    operator_id NUMBER(10),
    change_time DATE DEFAULT SYSDATE,
    remark      VARCHAR2(200),
    CONSTRAINT ck_osl_type CHECK (order_type IN ('采购单', '销售单', '退货单'))
);

COMMENT ON TABLE order_status_log IS '订单状态流转日志表：记录采购/销售/退货单的每一次状态变更';
COMMENT ON COLUMN order_status_log.order_type IS '订单类型：采购单/销售单/退货单';
COMMENT ON COLUMN order_status_log.order_id IS '对应订单主表的主键';
COMMENT ON COLUMN order_status_log.old_status IS '变更前状态（首次创建时为NULL）';
COMMENT ON COLUMN order_status_log.new_status IS '变更后状态';
COMMENT ON COLUMN order_status_log.operator_id IS '操作人编号';
COMMENT ON COLUMN order_status_log.change_time IS '状态变更时间';
COMMENT ON COLUMN order_status_log.remark IS '备注（如审批意见）';

CREATE INDEX idx_osl_order ON order_status_log(order_type, order_id);
CREATE INDEX idx_osl_operator ON order_status_log(operator_id);

-- 20. purchase_return_order
CREATE TABLE purchase_return_order (
    return_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_no    VARCHAR2(50) NOT NULL,
    purchase_id  NUMBER(10) NOT NULL,
    supplier_id  NUMBER(10) NOT NULL,
    operator_id  NUMBER(10) NOT NULL,
    return_date  DATE DEFAULT SYSDATE,
    total_amount NUMBER(12, 2) NOT NULL,
    status       VARCHAR2(20) DEFAULT '待审核',
    create_time  DATE DEFAULT SYSDATE,
    update_time  DATE,
    remark       VARCHAR2(200),
    CONSTRAINT uk_pro_return_no UNIQUE (return_no),
    CONSTRAINT fk_pro_purchase FOREIGN KEY (purchase_id) REFERENCES purchase_order(order_id),
    CONSTRAINT fk_pro_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id),
    CONSTRAINT fk_pro_operator FOREIGN KEY (operator_id) REFERENCES sys_user(user_id),
    CONSTRAINT ck_pro_status CHECK (status IN ('待审核', '已审核', '已完成', '已作废'))
);

COMMENT ON TABLE purchase_return_order IS '采购退货单主表：处理向供应商退货的业务单据';
COMMENT ON COLUMN purchase_return_order.return_id IS '采购退货单编号';
COMMENT ON COLUMN purchase_return_order.return_no IS '采购退货单号';
COMMENT ON COLUMN purchase_return_order.purchase_id IS '关联的原采购订单编号';
COMMENT ON COLUMN purchase_return_order.supplier_id IS '供应商编号';
COMMENT ON COLUMN purchase_return_order.operator_id IS '经办人编号';
COMMENT ON COLUMN purchase_return_order.return_date IS '退货日期';
COMMENT ON COLUMN purchase_return_order.total_amount IS '退货总金额';
COMMENT ON COLUMN purchase_return_order.status IS '退货单状态';
COMMENT ON COLUMN purchase_return_order.create_time IS '创建时间';
COMMENT ON COLUMN purchase_return_order.update_time IS '最后状态变更时间';
COMMENT ON COLUMN purchase_return_order.remark IS '备注';

CREATE INDEX idx_pro_purchase ON purchase_return_order(purchase_id);
CREATE INDEX idx_pro_supplier ON purchase_return_order(supplier_id);
CREATE INDEX idx_pro_operator ON purchase_return_order(operator_id);

-- 21. purchase_return_order_detail
CREATE TABLE purchase_return_order_detail (
    detail_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id    NUMBER(10) NOT NULL,
    product_id   NUMBER(10) NOT NULL,
    quantity     NUMBER(10) NOT NULL,
    return_price NUMBER(10, 2) NOT NULL,
    subtotal     NUMBER(12, 2) NOT NULL,
    CONSTRAINT fk_prod_return FOREIGN KEY (return_id) REFERENCES purchase_return_order(return_id),
    CONSTRAINT fk_prod_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE purchase_return_order_detail IS '采购退货单明细表';
COMMENT ON COLUMN purchase_return_order_detail.return_id IS '采购退货单编号';
COMMENT ON COLUMN purchase_return_order_detail.product_id IS '商品编号';
COMMENT ON COLUMN purchase_return_order_detail.quantity IS '退货数量';
COMMENT ON COLUMN purchase_return_order_detail.return_price IS '退货单价';
COMMENT ON COLUMN purchase_return_order_detail.subtotal IS '该行退款小计';

CREATE INDEX idx_prod_return ON purchase_return_order_detail(return_id);
CREATE INDEX idx_prod_product ON purchase_return_order_detail(product_id);

-- 22. coupon_template
CREATE TABLE coupon_template (
    template_id  NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coupon_name  VARCHAR2(100) NOT NULL,
    coupon_type  VARCHAR2(20) NOT NULL,
    min_amount   NUMBER(12, 2) DEFAULT 0,
    face_value   NUMBER(12, 2) NOT NULL,
    max_discount NUMBER(12, 2),
    valid_days   NUMBER(5) NOT NULL,
    total_count  NUMBER(10) DEFAULT 0,
    status       VARCHAR2(20) DEFAULT '启用',
    create_time  DATE DEFAULT SYSDATE,
    CONSTRAINT ck_ct_type CHECK (coupon_type IN ('满减券', '折扣券', '现金券')),
    CONSTRAINT ck_ct_status CHECK (status IN ('启用', '禁用'))
);

COMMENT ON TABLE coupon_template IS '优惠券模板表：定义一种优惠券的规则与发放总量';
COMMENT ON COLUMN coupon_template.coupon_name IS '优惠券名称';
COMMENT ON COLUMN coupon_template.coupon_type IS '券类型：满减券/折扣券/现金券';
COMMENT ON COLUMN coupon_template.min_amount IS '使用门槛金额';
COMMENT ON COLUMN coupon_template.face_value IS '面值（满减券=减X元，折扣券=0.85折，现金券=抵扣X元）';
COMMENT ON COLUMN coupon_template.max_discount IS '折扣券最高抵扣金额';
COMMENT ON COLUMN coupon_template.valid_days IS '领券后有效天数';
COMMENT ON COLUMN coupon_template.total_count IS '发放总量';
COMMENT ON COLUMN coupon_template.status IS '状态';

-- 23. member_coupon
CREATE TABLE member_coupon (
    coupon_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id  NUMBER(10) NOT NULL,
    member_id    NUMBER(10) NOT NULL,
    status       VARCHAR2(20) DEFAULT '未使用',
    receive_time DATE DEFAULT SYSDATE,
    use_time     DATE,
    sale_id      NUMBER(10),
    CONSTRAINT fk_mc_template FOREIGN KEY (template_id) REFERENCES coupon_template(template_id),
    CONSTRAINT fk_mc_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_mc_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    CONSTRAINT ck_mc_status CHECK (status IN ('未使用', '已使用', '已过期'))
);

COMMENT ON TABLE member_coupon IS '会员持有优惠券表：记录每张已发放优惠券的归属与使用状态';
COMMENT ON COLUMN member_coupon.template_id IS '优惠券模板编号';
COMMENT ON COLUMN member_coupon.member_id IS '持有会员编号';
COMMENT ON COLUMN member_coupon.status IS '券状态：未使用/已使用/已过期';
COMMENT ON COLUMN member_coupon.receive_time IS '领取时间';
COMMENT ON COLUMN member_coupon.use_time IS '使用时间';
COMMENT ON COLUMN member_coupon.sale_id IS '使用该券的销售单编号';

CREATE INDEX idx_mc_template ON member_coupon(template_id);
CREATE INDEX idx_mc_member ON member_coupon(member_id);
CREATE INDEX idx_mc_sale ON member_coupon(sale_id);

-- 24. point_config
CREATE TABLE point_config (
    config_id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    earn_rate       NUMBER(5, 2) NOT NULL,
    redeem_rate     NUMBER(5, 2) NOT NULL,
    redeem_min      NUMBER(10) DEFAULT 0,
    redeem_max_rate NUMBER(5, 2) DEFAULT 0.5,
    status          VARCHAR2(20) DEFAULT '启用',
    update_time     DATE DEFAULT SYSDATE,
    CONSTRAINT ck_pc_status CHECK (status IN ('启用', '禁用'))
);

COMMENT ON TABLE point_config IS '积分规则配置表：定义积分获取与抵扣比例';
COMMENT ON COLUMN point_config.earn_rate IS '积分获取率（如0.01=消费100元得1积分）';
COMMENT ON COLUMN point_config.redeem_rate IS '积分抵扣率（如0.01=1积分抵0.01元）';
COMMENT ON COLUMN point_config.redeem_min IS '最低使用积分数量';
COMMENT ON COLUMN point_config.redeem_max_rate IS '单笔订单积分抵扣比例上限（如0.5=最多抵50%）';
COMMENT ON COLUMN point_config.status IS '状态';
COMMENT ON COLUMN point_config.update_time IS '最后修改时间';

-- 25. transfer_order
CREATE TABLE transfer_order (
    transfer_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_no    VARCHAR2(50) NOT NULL,
    from_warehouse NUMBER(10) NOT NULL,
    to_warehouse   NUMBER(10) NOT NULL,
    status         VARCHAR2(20) DEFAULT '待审核',
    applicant_id   NUMBER(10) NOT NULL,
    approver_id    NUMBER(10),
    create_time    DATE DEFAULT SYSDATE,
    complete_time  DATE,
    remark         VARCHAR2(200),
    CONSTRAINT uk_transfer_no UNIQUE (transfer_no),
    CONSTRAINT fk_to_from_wh FOREIGN KEY (from_warehouse) REFERENCES warehouse(warehouse_id),
    CONSTRAINT fk_to_to_wh FOREIGN KEY (to_warehouse) REFERENCES warehouse(warehouse_id),
    CONSTRAINT fk_to_applicant FOREIGN KEY (applicant_id) REFERENCES sys_user(user_id),
    CONSTRAINT fk_to_approver FOREIGN KEY (approver_id) REFERENCES sys_user(user_id),
    CONSTRAINT ck_to_status CHECK (status IN ('待审核', '已审核', '已完成', '已取消'))
);

COMMENT ON TABLE transfer_order IS '调拨单主表：处理商品在不同仓库/门店之间的转移';
COMMENT ON COLUMN transfer_order.transfer_no IS '调拨单号';
COMMENT ON COLUMN transfer_order.from_warehouse IS '源仓库编号';
COMMENT ON COLUMN transfer_order.to_warehouse IS '目标仓库编号';
COMMENT ON COLUMN transfer_order.status IS '调拨单状态';
COMMENT ON COLUMN transfer_order.applicant_id IS '申请人编号';
COMMENT ON COLUMN transfer_order.approver_id IS '审批人编号';
COMMENT ON COLUMN transfer_order.create_time IS '创建时间';
COMMENT ON COLUMN transfer_order.complete_time IS '调拨完成时间';
COMMENT ON COLUMN transfer_order.remark IS '备注';

CREATE INDEX idx_to_from_wh ON transfer_order(from_warehouse);
CREATE INDEX idx_to_to_wh ON transfer_order(to_warehouse);
CREATE INDEX idx_to_applicant ON transfer_order(applicant_id);
CREATE INDEX idx_to_approver ON transfer_order(approver_id);

-- 26. transfer_order_detail
CREATE TABLE transfer_order_detail (
    detail_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id NUMBER(10) NOT NULL,
    product_id  NUMBER(10) NOT NULL,
    quantity    NUMBER(10) NOT NULL,
    CONSTRAINT fk_tod_transfer FOREIGN KEY (transfer_id) REFERENCES transfer_order(transfer_id),
    CONSTRAINT fk_tod_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE transfer_order_detail IS '调拨单明细表';
COMMENT ON COLUMN transfer_order_detail.transfer_id IS '调拨单编号';
COMMENT ON COLUMN transfer_order_detail.product_id IS '商品编号';
COMMENT ON COLUMN transfer_order_detail.quantity IS '调拨数量';

CREATE INDEX idx_tod_transfer ON transfer_order_detail(transfer_id);
CREATE INDEX idx_tod_product ON transfer_order_detail(product_id);

-- 27. stock_check_order
CREATE TABLE stock_check_order (
    check_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_no      VARCHAR2(50) NOT NULL,
    warehouse_id  NUMBER(10) NOT NULL,
    check_type    VARCHAR2(20) DEFAULT '定期盘点',
    status        VARCHAR2(20) DEFAULT '盘点中',
    operator_id   NUMBER(10) NOT NULL,
    check_date    DATE DEFAULT SYSDATE,
    complete_date DATE,
    remark        VARCHAR2(200),
    CONSTRAINT uk_check_no UNIQUE (check_no),
    CONSTRAINT fk_sco_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse(warehouse_id),
    CONSTRAINT fk_sco_operator FOREIGN KEY (operator_id) REFERENCES sys_user(user_id),
    CONSTRAINT ck_sco_type CHECK (check_type IN ('定期盘点', '动态盘点')),
    CONSTRAINT ck_sco_status CHECK (status IN ('盘点中', '已完成', '已作废'))
);

COMMENT ON TABLE stock_check_order IS '库存盘点单主表：记录盘点任务与执行状态';
COMMENT ON COLUMN stock_check_order.check_no IS '盘点单号';
COMMENT ON COLUMN stock_check_order.warehouse_id IS '盘点仓库编号';
COMMENT ON COLUMN stock_check_order.check_type IS '盘点类型：定期盘点/动态盘点';
COMMENT ON COLUMN stock_check_order.status IS '盘点单状态';
COMMENT ON COLUMN stock_check_order.operator_id IS '盘点操作人编号';
COMMENT ON COLUMN stock_check_order.check_date IS '盘点日期';
COMMENT ON COLUMN stock_check_order.complete_date IS '盘点完成日期';
COMMENT ON COLUMN stock_check_order.remark IS '备注';

CREATE INDEX idx_sco_warehouse ON stock_check_order(warehouse_id);
CREATE INDEX idx_sco_operator ON stock_check_order(operator_id);

-- 28. stock_check_detail
CREATE TABLE stock_check_detail (
    detail_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_id       NUMBER(10) NOT NULL,
    product_id     NUMBER(10) NOT NULL,
    system_qty     NUMBER(10) NOT NULL,
    actual_qty     NUMBER(10) NOT NULL,
    difference_qty NUMBER(10) NOT NULL,
    adjust_price   NUMBER(10, 2),
    adjust_amount  NUMBER(12, 2),
    CONSTRAINT fk_scd_check FOREIGN KEY (check_id) REFERENCES stock_check_order(check_id),
    CONSTRAINT fk_scd_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

COMMENT ON TABLE stock_check_detail IS '库存盘点明细表：逐商品比对系统库存与实际库存';
COMMENT ON COLUMN stock_check_detail.check_id IS '盘点单编号';
COMMENT ON COLUMN stock_check_detail.product_id IS '商品编号';
COMMENT ON COLUMN stock_check_detail.system_qty IS '系统库存数量';
COMMENT ON COLUMN stock_check_detail.actual_qty IS '实际盘点数量';
COMMENT ON COLUMN stock_check_detail.difference_qty IS '差异数量（实际-系统，正=盘盈，负=盘亏）';
COMMENT ON COLUMN stock_check_detail.adjust_price IS '调整单价';
COMMENT ON COLUMN stock_check_detail.adjust_amount IS '损益金额';

CREATE INDEX idx_scd_check ON stock_check_detail(check_id);
CREATE INDEX idx_scd_product ON stock_check_detail(product_id);

-- 29. daily_settlement
CREATE TABLE daily_settlement (
    settlement_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_date    DATE NOT NULL,
    total_sales        NUMBER(12, 2) DEFAULT 0,
    cash_amount        NUMBER(12, 2) DEFAULT 0,
    wechat_amount      NUMBER(12, 2) DEFAULT 0,
    alipay_amount      NUMBER(12, 2) DEFAULT 0,
    promotion_discount NUMBER(12, 2) DEFAULT 0,
    member_discount    NUMBER(12, 2) DEFAULT 0,
    coupon_deduct      NUMBER(12, 2) DEFAULT 0,
    point_deduct       NUMBER(12, 2) DEFAULT 0,
    point_consumed     NUMBER(10) DEFAULT 0,
    order_count        NUMBER(10) DEFAULT 0,
    status             VARCHAR2(20) DEFAULT '已生成',
    create_time        DATE DEFAULT SYSDATE,
    CONSTRAINT uk_settlement_date UNIQUE (settlement_date),
    CONSTRAINT ck_ds_status CHECK (status IN ('已生成', '已确认'))
);

COMMENT ON TABLE daily_settlement IS '每日营业结转表：记录每日闭店后的销售汇总与各项优惠拆分';
COMMENT ON COLUMN daily_settlement.settlement_date IS '结转日期（唯一，一天一条）';
COMMENT ON COLUMN daily_settlement.total_sales IS '当日销售总额（实收合计）';
COMMENT ON COLUMN daily_settlement.cash_amount IS '现金实收金额';
COMMENT ON COLUMN daily_settlement.wechat_amount IS '微信实收金额';
COMMENT ON COLUMN daily_settlement.alipay_amount IS '支付宝实收金额';
COMMENT ON COLUMN daily_settlement.promotion_discount IS '限时特价让利总额';
COMMENT ON COLUMN daily_settlement.member_discount IS '会员折扣让利总额';
COMMENT ON COLUMN daily_settlement.coupon_deduct IS '优惠券核销总额';
COMMENT ON COLUMN daily_settlement.point_deduct IS '积分抵扣金额';
COMMENT ON COLUMN daily_settlement.point_consumed IS '消耗积分总数';
COMMENT ON COLUMN daily_settlement.order_count IS '当日订单总数';
COMMENT ON COLUMN daily_settlement.status IS '结转状态';
COMMENT ON COLUMN daily_settlement.create_time IS '生成时间';
