-- ============================================================
-- 03_data.sql：测试数据扩充脚本（在 02_data.sql 基础上追加执行）
--
-- 用途：
--   1. 预警功能测试：新增 150 个演示商品，其中 30 个库存达到或低于预警值，
--      前端「库存管理-库存预警」应能展示这 30 个商品。
--   2. 翻页功能测试：商品/库存/库存流水表从个位数扩充到 150+ 行，
--      前端列表按每页 10 条应出现 15 页以上。
--
-- 说明：
--   - 纯追加（只 INSERT 新行），不清除 02 的种子数据。
--   - 商品/库存/流水三个表配套插入，保证库存与流水余额一致。
--   - 末尾同步 Identity 序列（与 02 同样的模式），避免后续业务
--     自增主键与显式插入的主键冲突。
-- ============================================================

-- ------------------------------------------------------------
-- 1. 新增 150 个演示商品（product_id 6..155）
--    类别/供应商在 1..3 之间轮转，条码唯一，价格按公式生成
-- ------------------------------------------------------------
BEGIN
    FOR i IN 1..150 LOOP
        INSERT INTO product (product_id, category_id, supplier_id, product_name,
                             barcode, specification, purchase_price, sale_price,
                             is_promotion, promotion_price, stock_warning, unit, status)
        VALUES (
            5 + i,
            MOD(i, 3) + 1,                                        -- 类别 1/2/3 轮转
            MOD(i, 3) + 1,                                        -- 供应商 1/2/3 轮转
            '演示商品' || LPAD(i, 3, '0'),                         -- 演示商品001..150
            '6900000' || LPAD(5 + i, 5, '0'),                     -- 12位唯一条码
            '测试规格' || i,
            ROUND(1 + MOD(i, 50) * 0.5, 2),                       -- 进价
            ROUND((1 + MOD(i, 50) * 0.5) * 1.4, 2),               -- 售价
            CASE WHEN MOD(i, 20) = 0 THEN '是' ELSE '否' END,     -- 每20个设1个促销
            NULL,
            10 + MOD(i, 10) * 5,                                  -- 预警值 10..55
            CASE MOD(i, 3) WHEN 0 THEN '件' WHEN 1 THEN '袋' ELSE '瓶' END,
            '在售'
        );
    END LOOP;
    COMMIT;
END;
/

-- ------------------------------------------------------------
-- 2. 为每个新商品建库存记录（单仓库总仓，warehouse_id=1）
--    预警规则：
--      i mod 10 = 0  → 库存恰好等于预警值（触发预警）
--      i mod 10 = 1  → 库存低于预警值    （触发预警）
--      其余          → 库存充足           （不触发）
--    150 个商品中恰有 30 个触发预警（15 个达标 + 15 个低于）
-- ------------------------------------------------------------
BEGIN
    FOR i IN 1..150 LOOP
        INSERT INTO inventory (inventory_id, product_id, warehouse_id, current_stock, last_update_time)
        VALUES (
            5 + i,
            5 + i,
            1,                                                      -- 总仓
            CASE
                WHEN MOD(i, 10) = 0 THEN 10 + MOD(i, 10) * 5       -- 等于预警值
                WHEN MOD(i, 10) = 1 THEN 10 + MOD(i, 10) * 5 - 2   -- 低于预警值
                ELSE 10 + MOD(i, 10) * 5 + 100                     -- 库存充足
            END,
            SYSDATE
        );
    END LOOP;
    COMMIT;
END;
/

-- ------------------------------------------------------------
-- 3. 为每个新商品补一条「入库」流水（余额与库存表一致）
-- ------------------------------------------------------------
BEGIN
    FOR i IN 1..150 LOOP
        INSERT INTO inventory_record (record_id, product_id, record_type, source_no,
                                      change_qty, remain_qty, operator_id, record_time, remark)
        SELECT
            5 + i,
            5 + i,
            '入库',
            '03批量入库',
            current_stock,                                          -- 期初入库数量
            current_stock,                                          -- 变动后余额与库存一致
            2,                                                      -- 操作人：采购员 buyer01
            SYSDATE,
            '03测试数据批量入库'
        FROM inventory
        WHERE inventory_id = 5 + i;
    END LOOP;
    COMMIT;
END;
/

-- ------------------------------------------------------------
-- 4. 同步 Identity 序列（与 02_data.sql 末尾同样的模式）
--    本次显式写入主键到 155，把序列推进到当前最大值 + 1
-- ------------------------------------------------------------
ALTER TABLE product MODIFY (product_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE inventory MODIFY (inventory_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE inventory_record MODIFY (record_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));

COMMIT;
