-- ============================================================
-- 04_data.sql：供应商测试数据扩充（在 02/03_data.sql 基础上追加执行）
--
-- 用途：
--   1. 供应商从 3 家扩充到 33 家，采购/结算/退货模块联调时有更多选择。
--   2. 供应商列表翻页测试：每页 10 条可翻 3 页以上。
--
-- 说明：
--   - 纯追加（只 INSERT 新行），不清除 02/03 的数据。
--   - 供应商编号 4..33（02 已占用 1..3）。
--   - 信用等级 A/B/C 轮转；结算周期 15/30/45 轮转；
--     每 10 家设 1 家「禁用」，其余「启用」。
--   - 末尾同步 Identity 序列，避免后续自增主键冲突。
-- ============================================================

BEGIN
    FOR i IN 1..30 LOOP
        INSERT INTO supplier (supplier_id, supplier_name, contact_name, phone, email,
                              address, credit_level, payment_cycle, min_order_qty,
                              bank_name, bank_account, status)
        VALUES (
            3 + i,
            '测试供应商' || LPAD(i, 2, '0'),                        -- 测试供应商01..30
            '联系人' || LPAD(i, 2, '0'),
            '021-6000' || LPAD(1000 + i, 4, '0'),
            'test' || LPAD(3 + i, 2, '0') || '@supplier.com',
            '测试地址' || LPAD(i, 2, '0') || '号',
            CASE MOD(i, 3) WHEN 0 THEN 'A' WHEN 1 THEN 'B' ELSE 'C' END,
            CASE MOD(i, 3) WHEN 0 THEN 15 WHEN 1 THEN 30 ELSE 45 END,
            10 + MOD(i, 5) * 5,
            '测试银行' || LPAD(i, 2, '0'),
            '62220000' || LPAD(1000000 + i, 8, '0'),
            CASE WHEN MOD(i, 10) = 0 THEN '禁用' ELSE '启用' END    -- 每10家1家禁用
        );
    END LOOP;
    COMMIT;
END;
/

-- 同步 Identity 序列（与 02/03 末尾同样的模式）
ALTER TABLE supplier MODIFY (supplier_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));

COMMIT;
