-- ============================================================
-- 05_data.sql：测试供应商商品配对脚本（在 02/03/04_data.sql 基础上追加执行）
--
-- 用途：
--   给 04 扩充的 30 家测试供应商（supplier_id 4..33）各配 10 个商品，
--   共 300 个（product_id 156..455）。商品与供应商绑定（product.supplier_id），
--   前端「按供应商过滤商品」修复后，采购流程可用测试供应商完整跑通。
--
-- 说明：
--   - 纯追加（只 INSERT 新行），不清除 02/03/04 的数据。
--   - 每家第 10 个商品库存恰好等于预警值（触发预警），其余库存充足。
--   - 商品/库存/流水三个表配套插入，余额一致。
--   - 末尾同步 Identity 序列，避免后续自增主键冲突。
-- ============================================================

DECLARE
    v_pid      NUMBER;
    v_warning  NUMBER;
    v_stock    NUMBER;
    v_name     VARCHAR2(100);
BEGIN
    FOR i IN 1..30 LOOP                        -- 30 家测试供应商（supplier_id = 3 + i）
        FOR j IN 1..10 LOOP                    -- 每家 10 个商品
            v_pid     := 155 + (i - 1) * 10 + j;
            v_warning := 10 + MOD(v_pid, 10) * 5;
            v_stock   := CASE WHEN j = 10 THEN v_warning ELSE v_warning + 100 END;
            v_name    := '供应商' || LPAD(3 + i, 2, '0') || '商品' || LPAD(j, 2, '0');

            INSERT INTO product (product_id, category_id, supplier_id, product_name,
                                 barcode, specification, purchase_price, sale_price,
                                 is_promotion, promotion_price, stock_warning, unit, status)
            VALUES (
                v_pid,
                MOD(v_pid, 3) + 1,
                3 + i,
                v_name,
                '690000' || LPAD(v_pid, 6, '0'),                -- 12位唯一条码
                '测试规格' || v_pid,
                ROUND(2 + MOD(v_pid, 50) * 0.5, 2),
                ROUND((2 + MOD(v_pid, 50) * 0.5) * 1.4, 2),
                '否',
                NULL,
                v_warning,
                CASE MOD(v_pid, 3) WHEN 0 THEN '件' WHEN 1 THEN '袋' ELSE '瓶' END,
                '在售'
            );

            INSERT INTO inventory (inventory_id, product_id, warehouse_id, current_stock, last_update_time)
            VALUES (v_pid, v_pid, 1, v_stock, SYSDATE);

            INSERT INTO inventory_record (record_id, product_id, record_type, source_no,
                                          change_qty, remain_qty, operator_id, record_time, remark)
            VALUES (v_pid, v_pid, '入库', '05批量入库', v_stock, v_stock, 2, SYSDATE, '05测试数据批量入库');
        END LOOP;
    END LOOP;
    COMMIT;
END;
/

-- 同步 Identity 序列（与 02/03/04 末尾同样的模式）
ALTER TABLE product MODIFY (product_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE inventory MODIFY (inventory_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE inventory_record MODIFY (record_id GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE));

COMMIT;
