-- 创建商品类别表
CREATE TABLE product_category (
    category_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 自增主键
    category_name VARCHAR2(50) NOT NULL UNIQUE,                             -- 类别名称，唯一且必填
    category_desc VARCHAR2(200),                                            -- 类别描述
    status        VARCHAR2(20) DEFAULT '启用'                                -- 状态：启用/禁用
);

-- 添加注释
COMMENT ON TABLE product_category IS '商品类别表';
COMMENT ON COLUMN product_category.category_name IS '类别名称，如食品、日用品等';