-- 创建商品信息表
CREATE TABLE product (
    product_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 商品编号
    category_id    NUMBER(10) NOT NULL,                                     -- 外键：引用表5
    supplier_id    NUMBER(10) NOT NULL,                                     -- 外键：引用表7
    product_name   VARCHAR2(100) NOT NULL,                                  -- 商品名称
    barcode        VARCHAR2(50) UNIQUE,                                     -- 条码，全库唯一
    specification  VARCHAR2(100),                                           -- 规格说明
    purchase_price NUMBER(10, 2) DEFAULT 0,                                 -- 进价
    sale_price     NUMBER(10, 2) DEFAULT 0,                                 -- 零售价
    stock_warning  NUMBER(10) DEFAULT 10,                                   -- 库存预警阈值
    unit           VARCHAR2(20),                                            -- 单位
    status         VARCHAR2(20) DEFAULT '在售',                              -- 状态：在售/停售
    
    -- 【外键约束批注】：
    -- 确保引用表5的类别ID
    CONSTRAINT fk_prod_category FOREIGN KEY (category_id) 
        REFERENCES product_category(category_id),
    -- 确保引用表7的供应商ID（需先建立表7）
    CONSTRAINT fk_prod_supplier FOREIGN KEY (supplier_id) 
        REFERENCES supplier(supplier_id)
);

-- 添加注释
COMMENT ON TABLE product IS '商品基础资料表';