-- 创建角色菜单关联表
CREATE TABLE sys_role_menu (
    role_menu_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 关联主键
    role_id      NUMBER(10) NOT NULL,                                     -- 外键：引用表2
    menu_id      NUMBER(10) NOT NULL,                                     -- 外键：引用表3
    
    -- 【外键约束批注】：
    -- 关联角色表
    CONSTRAINT fk_rm_role FOREIGN KEY (role_id) 
        REFERENCES sys_role(role_id) ON DELETE CASCADE,
    -- 关联菜单表
    CONSTRAINT fk_rm_menu FOREIGN KEY (menu_id) 
        REFERENCES sys_menu(menu_id) ON DELETE CASCADE,
    
    -- 唯一约束：同一个角色不能重复分配同一个菜单
    CONSTRAINT uk_role_menu UNIQUE (role_id, menu_id)
);

-- 添加注释
COMMENT ON TABLE sys_role_menu IS '权限中间表：定义哪些角色可以访问哪些菜单';