-- 创建供应商结算表
CREATE TABLE supplier_settlement (
    settlement_id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 结算编号
    supplier_id      NUMBER(10) NOT NULL,                                     -- 供应商编号 (FK)
    purchase_id      NUMBER(10) NOT NULL,                                     -- 采购单编号 (FK)
    settlement_date  DATE DEFAULT SYSDATE,                                    -- 结算日期
    settlement_amount NUMBER(12, 2) NOT NULL,                                 -- 结算金额
    paid_amount      NUMBER(12, 2) DEFAULT 0,                                 -- 已付金额
    unpaid_amount    NUMBER(12, 2) NOT NULL,                                  -- 未付金额
    status           VARCHAR2(20) NOT NULL,                                   -- 结算状态
    remark           VARCHAR2(200),                                           -- 备注
    
    -- 外键约束
    CONSTRAINT fk_ss_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(supplier_id),
    CONSTRAINT fk_ss_purchase FOREIGN KEY (purchase_id) REFERENCES purchase_order(purchase_id)
    -- 检查约束：确保变动类型属于3种中的一个
    CONSTRAINT ck_ss_status CHECK (status IN ('未结算', '已结算', '部分结算'))
);

COMMENT ON TABLE supplier_settlement IS '供应商结算表：管理与供应商的财务结账情况';
