-- 创建积分流水表
CREATE TABLE point_record (
    point_record_id  NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 积分流水编号
    member_id        NUMBER(10) NOT NULL,                                     -- 会员编号 (FK)
    sale_id          NUMBER(10),                                              -- 销售单编号 (FK，可空)
    change_type      VARCHAR2(20) NOT NULL,                                   -- 积分变动类型
    change_points    NUMBER(10) NOT NULL,                                     -- 变动积分
    remain_points    NUMBER(10) NOT NULL,                                     -- 剩余积分
    record_time      DATE DEFAULT SYSDATE,                                    -- 记录时间
    remark           VARCHAR2(200),                                           -- 备注
    
    -- 外键约束
    CONSTRAINT fk_pr_member FOREIGN KEY (member_id) REFERENCES member(member_id),
    CONSTRAINT fk_pr_sale FOREIGN KEY (sale_id) REFERENCES sale_order(sale_id),
    -- 检查约束：确保变动类型属于3种中的一个
    CONSTRAINT ck_pr_type CHECK (change_type IN ('增加','扣减','抵现'))
);

COMMENT ON TABLE point_record IS '积分流水表：记录会员积分的每一次增减变动历史';
COMMENT ON COLUMN point_record.sale_id IS '关联销售单，记录是哪笔交易产生的积分变动；若是其他活动导致积分变化时可为空';