-- 创建退货单明细表
CREATE TABLE return_order_detail (
    return_detail_id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 明细编号
    return_id        NUMBER(10) NOT NULL,                                     -- 退货单编号 (FK)
    product_id       NUMBER(10) NOT NULL,                                     -- 商品编号 (FK)
    quantity         NUMBER(10) NOT NULL,                                     -- 退货数量
    refund_price     NUMBER(10, 2) NOT NULL,                                  -- 退货单价
    subtotal         NUMBER(12, 2) NOT NULL,                                  -- 小计金额
    
    -- 外键约束
    CONSTRAINT fk_rod_return FOREIGN KEY (return_id) REFERENCES return_order(return_id) ON DELETE CASCADE, --级联
    CONSTRAINT fk_rod_product FOREIGN KEY (product_id) REFERENCES product(product_id)
);

-- 注释
COMMENT ON TABLE return_order_detail IS '退货单明细表：记录每一笔退货业务中包含的具体商品、数量及退款单价';
COMMENT ON COLUMN return_order_detail.refund_price IS '退货单价';
COMMENT ON COLUMN return_order_detail.subtotal IS '该笔商品退款总计金额';